name: Publish VS Code extension

on:
  workflow_dispatch:
    inputs:
      version:
        required: true

jobs:
  publish-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - run: npm ci
      - run: npx vsce publish ${{ github.event.inputs.version }} --pat ${{ secrets.VSCODE_MARKETPLACE_TOKEN }} --packagePath ./dist/auto-typing-final.vsix
